[tool]
[tool.poetry]
name = "MisakiUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy MisakiUserBot to Heroku"
authors = ["Misaki"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
